### ISSUE TITLE
Performance improvement in XObserver

### ISSUE THREAD

**Issue by stephane-vanraes** [Hugos68/action-archive#36]
Having one common Observer component offers a significant improvement over instantiating a new Observer for each occurence. This can be done by moving the `new IntersectionObserver()` outside of the action call (it will then be called first time this action is used) and attaching the observations to that one.

there is a bit of reading here (it uses angular, but the same applies) https://www.bennadel.com/blog/3954-intersectionobserver-api-performance-many-vs-shared-in-angular-11-0-5.htm
also this SO question talks about it https://stackoverflow.com/questions/55867849/one-intersectionobserver-to-observe-many-elements-or-one-intersectionobserver-pe

**Comment by Hugos68** [comment]
I implemented your suggested changes using a Map to keep track of which parameter sets already have an observer or not, this means if you pass 2 actions with identical parameters they will use the same observer. This will still be flawed when using the same root element and the root element is in different states because I am currently using JSON.stringify to compare the passed in parameters. Let me know if you have any more questions reqarding this.
ps: I also implemented this for the resize observer

**Comment by stephane-vanraes** [comment]
I had a look at what I was doing at work, and the general principles is like this ```js
const observed = new Map();
const observer = new MutationObserver(entries => {
  entries.forEach(entry => {
    const options = observed.get(entry.target);
    // do something with options
    entry.target.dispatchEvent(new CustomEvent('mutated', entry))
  })	
});

export default function mutate(node, options) {
  observed.set(node, options);
  observer.observe(node, options)

  return {
    destroy() {
      observed.delete(node);
    }
  }
}
```

I also noticed this probably will not be applicable to `IntersectionObserver` as there you pass in the options when creating the observer instead of when you start observing, so you will probably not do it there.

**Comment by Hugos68** [comment]
@stephane-vanraes I just realized I accidentally edited your comment (WHY IS THIS A FEATURE GITHUB, ARGH), could you re redit and enter your message? Sorry.

**Comment by stephane-vanraes** [comment]
> @stephane-vanraes I just realized I accidentally edited your comment (WHY IS THIS A FEATURE GITHUB, ARGH), could you re redit and enter your message? Sorry.

it's a feature because you should be able to edit out / delete offensive comments.  You can access the edit history though (not sure if everyone has the right to do so though. there should be a little arrow next to "edited"

**Comment by Hugos68** [comment]
So I am looking at this again and although I really like the performance benefit, I think if folks really want to get this performance boost they can simply copy the action into their codebase and edit it accordingly. Since I'd have to sacrifice using different configurations if I wanted to use 1 universal observer. I will close this for now but do let me know if it needs to be reopened, either way thanks for showing me and others this, this is valueable.
